[package]
name = "tagsearch"
version = "0.9.0"
authors = ["Chris Davison <c.jr.davison@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
glob = "0.3.0"
lazy_static = "1.4.0"
structopt = "0.3.3"
